[settings]

# Enable animations.
animate = true

# Disable each space by default. When this is set, Use the
# toggle_space_activated command to enable a space.
default_disable = false

# Focus the window under the mouse as it moves.
focus_follows_mouse = false

# Move the mouse to the middle of the window each time the focus changes.
mouse_follows_focus = false

[keys]
# Note: Modifier and key names must be capitalized.

# Save the current state to the restore file and exit.
# Restore this with the --restore option when starting glide.
# Note that the restore file is only useful when upgrading or restarting
# glide itself; it is not valid after the user logs out or restarts.
"Alt + Shift + E" = "save_and_exit"

# Toggle whether the current space is managed by Glide.
"Alt + Z" = "toggle_space_activated"

# Focus the window in the specified direction.
"Alt + H" = { move_focus = "left" }
"Alt + J" = { move_focus = "down" }
"Alt + K" = { move_focus = "up" }
"Alt + L" = { move_focus = "right" }

# Move the focused window in the specified direction.
"Alt + Shift + H" = { move_node = "left" }
"Alt + Shift + J" = { move_node = "down" }
"Alt + Shift + K" = { move_node = "up" }
"Alt + Shift + L" = { move_node = "right" }

# Resize the focused window in the specified direction by percentage.
"Alt + Ctrl + H" = { resize = { direction = "left", percent = 5 } }
"Alt + Ctrl + J" = { resize = { direction = "down", percent = 5 } }
"Alt + Ctrl + K" = { resize = { direction = "up", percent = 5 } }
"Alt + Ctrl + L" = { resize = { direction = "right", percent = 5 } }

# Move up or down the tree hieararchy, selecting a parent or child node
# respectively.
"Alt + A" = "ascend"
"Alt + D" = "descend"

# Toggle between saved layouts on the active space. This allows you to access
# layouts from other screen sizes.
"Alt + N" = "next_layout"
"Alt + P" = "prev_layout"

# Create a container above the current node in the specified orientation.
# This has the effect of "splitting" the current window/node once a new node
# is added.
"Alt + Backslash" = { split = "horizontal" }
"Alt + Equal" = { split = "vertical" }

# Change the parent node to a horizontal or vertical group, also known as
# "tabbed" and "stacked" respectively.
"Alt + T" = { group = "horizontal" }
"Alt + S" = { group = "vertical" }
"Alt + E" = "ungroup"

# Float the current node. Floating windows are allowed to overlap and keep
# whatever size and position you give them. Note that they do not actually
# float on top of other windows, as that would require disabling security
# protection on your machine.
"Alt + Shift + Space" = "toggle_window_floating"

# Toggle between focusing floating nodes. When switching to floating mode
# this will put all floating windows on top, and when switching away it will
# hide floating windows.
"Alt + Space" = "toggle_focus_floating"

# Toggle whether the focused node takes up the whole screen.
"Alt + Shift + F" = "toggle_fullscreen"

[settings.experimental]
# Show the current space index on the status icon.
status_icon.space_index = true

# Use color in the icon.
# status_icon.color = true
